### ISSUE TITLE
Reported that Stripe uses the old name instead of the new name when checking out.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-add-name-to-checkout#12]
Let's try to recreate this and see if we can come up with a fix.

**Comment by JarrydLong** [comment]
Figured out how to replicate this. 

Once you go through the checkout process, Stripe creates a 'customer' for you. On the initial purchase,  we use the `first_name` and `last_name` details, but if you're purchasing again and we've got your details, we'll use either what's stored or the `billing_name` if available. 

![image](https://user-images.githubusercontent.com/8989542/78668953-d5e5ce80-78db-11ea-8e1e-ef5570aa9794.png)

Working from the bottom up, 'admin' is what was stored already before using the plugin. 'Jarryd Pro was then used during checkout, saved to the profile but didn't go through to Stripe. Adjusted the code, checkout out again and it worked. Same applies for 'Jarryd Updated Acc'
