### ISSUE TITLE
PHP shortcut is not standard on all servers

### ISSUE THREAD

**Issue by rumspeed** [strangerstudios/pmpro-add-name-to-checkout#2]
I found an issue with using the PHP shortcut on my server. `<?` is the shortcut for `<?php` and is not always on by default on some servers. `<?php` is the full version and is usually recommended, as it will always works.

I changed these:
`<?=$first_name?>`
`<?=$last_name?>`

To these
`<?php echo $first_name ?>`
`<?php echo $last_name ?>`

And it worked just fine. This screenshot is from before I changed the code.

![pmp_-_php_issue](https://cloud.githubusercontent.com/assets/4145412/11247878/009b351e-8dec-11e5-96c1-711380519cc3.png)

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/pmpro-add-name-to-checkout/commit/79c1a81aee894a8da81e36e5075a1725e546ffa9 thanks
