### ISSUE TITLE
Payfast and Added firstname lastname

### ISSUE THREAD

**Issue by Wooze27** [strangerstudios/pmpro-add-name-to-checkout#23]
I have activated the plugin but the firstname and lastname are not being captured.
Am am using the payfast payment gateway/

**Comment by andrewlimaza** [comment]
Hi @Wooze27 

Are you still experiencing this issue? What version of the Add Name to Checkout were you using?

You can test the pre-release here -> https://github.com/strangerstudios/pmpro-add-name-to-checkout/pull/25
