### ISSUE TITLE
Map First and Last name to User First and Last Name Fields

### ISSUE THREAD

**Issue by vexersa** [strangerstudios/pmpro-add-name-to-checkout#29]
Hello, 

Thanks for the plugin!

Should user's first and last name values collected on checkout be populating WP's own first and last name fields? 

![image](https://user-images.githubusercontent.com/7994227/107146045-46230d80-694e-11eb-93f5-132da7e7d076.png)

In the above image:

- User ID 1 is the WP admin account, so has First and Last name fields populated.
- User ID 29 is a manually added PMPRO user so has First and Last name fields populated.
- User ID 30 is added through the PMPRO checkout form and although the display name is correct, the First and Last name fields do not have the respective values. 

When viewing the user's details through the WP Users menu, no first or last name appears, only the "Display name publicly as:" dropdown contains the respective user's first and last name.

**Comment by andrewlimaza** [comment]
Hi @vexersa

Yes this should, there's a minor bug with offsite gateways that we've come across and plan on resolving this.

**Comment by andrewlimaza** [comment]
This has been resolved in the latest update that is set to release, you may pull from the `dev` branch to pre-patch your site. Thank you for your patience.
