### ISSUE TITLE
Custom fields and billing address not saved / updated

### ISSUE THREAD

**Issue by tejasbusiness** [strangerstudios/pmpro-add-name-to-checkout#6]
Hello,

I am working on a client project and client happens to be an Indian, so naturally they want some Indian payment gateway to be integrated.

In the process, I have created a plugin for new payment gateway “Bill Desk”.

Payment gateway is tested and seems working fine. Test amount is being debited from my bank account and credited to my client’s bank account. So the payment process is working fine.

On the checkout page, I have added few custom fields like date of birth, alternate phone number, couple of dropdown and text area. Also have two custom fields where user need to upload Age proof document and Address proof document.

But when checked user profile and the email notification received as a result of new user, following problems are seen (User profile when seen from front-end or wp admin panel)

Problem Area
1. Billing Address 1, Billing Address 2, City, State, Zip, Country NOT being saved (updated), Billing Phone
   1. Extra fields:
      2a. Emergency Phone
      2b. Date of Birth
      2c. Work Experience
      and few more fields

**Comment by ngwebspinner** [comment]
Hi. May I ask how you resolved this?

**Comment by ideadude** [comment]
Sounds like an issue with a different set of code. Closing. Hope you were able to figure this out.
